apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    description: Database migrator for Postgres databases
  labels:
    app.component.kubernetes/component: migrator
    deploy: sourcegraph
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: index.docker.io/sourcegraph/migrator:5.2.7@sha256:09b8ddf2fc9b1ab88bffffb6d9795d9474b1a3792ea3c9b066f804400477bc08
          args: ["up"]
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
          resources:
            limits:
              cpu: 500m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
      restartPolicy: OnFailure
  backoffLimit: 4
