apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sourcegraph-frontend
    app.kubernetes.io/component: frontend
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: sourcegraph-frontend-env
data:
  PGHOST: "pgsql"
  PGPORT: "5432"
  PGUSER: "sg"
  PGPASSWORD: "sg"
  PGDATABASE: "sg"
  PGSSLMODE: "disable"
  CODEINTEL_PGHOST: "codeintel-db"
  CODEINTEL_PGPORT: "5432"
  CODEINTEL_PGUSER: "sg"
  CODEINTEL_PGPASSWORD: "sg"
  CODEINTEL_PGDATABASE: "sg"
  CODEINTEL_PGSSLMODE: "disable"
  CODEINSIGHTS_PGHOST: "codeinsights-db"
  CODEINSIGHTS_PGPORT: "5432"
  CODEINSIGHTS_PGUSER: "postgres"
  CODEINSIGHTS_PGPASSWORD: "password"
  CODEINSIGHTS_PGDATABASE: "postgres"
  CODEINSIGHTS_PGSSLMODE: "disable"
