# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: grafana
# spec:
#   template:
#     spec:
#       containers:
#         - name: grafana
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 472
#             runAsUser: 472
#       securityContext:
#         runAsUser: 472
#         fsGroup: 472
