# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: node-exporter
# spec:
#   template:
#     spec:
#       containers:
#         - name: node-exporter
#           securityContext:
#             allowPrivilegeEscalation: false
#             readOnlyRootFilesystem: true
#             runAsGroup: 65534
#             runAsUser: 65534
#       securityContext:
#         fsGroup: 65534
#         runAsGroup: 65534
#         runAsNonRoot: true
#         runAsUser: 65534
