apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - rbac/sourcegraph-frontend.Role.yaml
  - rbac/sourcegraph-frontend.RoleBinding.yaml
  - rbac/sourcegraph-frontend.ServiceAccount.yaml
patchesStrategicMerge:
  - patches/sourcegraph-frontend.Deployment.yaml
  - patches/sourcegraph-frontend.ConfigMap.yaml
