apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourcegraph-frontend
spec:
  template:
    spec:
      initContainers:
        - name: migrator
          securityContext:
            allowPrivilegeEscalation: true
            runAsGroup: 0
            runAsUser: 0
      containers:
        - name: frontend
          securityContext:
            allowPrivilegeEscalation: true
            runAsGroup: 0
            runAsUser: 0
          env:
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
      securityContext:
        runAsUser: 0
        fsGroup: 0
