# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: syntect-server
# spec:
#   template:
#     spec:
#       containers:
#         - name: syntect-server
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 101
#             runAsUser: 100
#       securityContext:
#         runAsUser: 100
#         fsGroup: 101
