# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis-cache
# spec:
#   template:
#     spec:
#       containers:
#         - name: redis-cache
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 1000
#             runAsUser: 999
#         - name: redis-exporter
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 1000
#             runAsUser: 999
#       securityContext:
#         runAsUser: 999
#         fsGroup: 1000
