# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: searcher
# spec:
#   template:
#     spec:
#       containers:
#         - name: searcher
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 101
#             runAsUser: 100
#       securityContext:
#         runAsUser: 100
#         fsGroup: 101
