# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sourcegraph-frontend
# spec:
#   template:
#     spec:
#       initContainers:
#         - name: migrator
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 101
#             runAsUser: 100
#       containers:
#         - name: frontend
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 101
#             runAsUser: 100
#       securityContext:
#         runAsUser: 100
#         fsGroup: 101
