apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - monitoring
  - ../../storage-class/k3s
  # - ../../privileged
patchesStrategicMerge:
  - patches/sourcegraph-frontend.Ingress.yaml
