apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: frontend
    description: Serves the frontend of Sourcegraph via HTTP(S).
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: frontend
  name: sourcegraph-frontend
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sourcegraph-frontend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sourcegraph-frontend
        deploy: sourcegraph
    spec:
      initContainers:
        - name: migrator
          image: index.docker.io/sourcegraph/migrator:5.2.7@sha256:09b8ddf2fc9b1ab88bffffb6d9795d9474b1a3792ea3c9b066f804400477bc08
          args: ["up"]
          resources:
            limits:
              cpu: 500m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsGroup: 101
            runAsUser: 100
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
      containers:
        - name: frontend
          image: index.docker.io/sourcegraph/frontend:5.2.7@sha256:10e1a311feb2c7ced6ca5f3f22401d717fd28c93ce65025cf7615519481f6435
          args:
            - serve
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
          # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
          env:
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          terminationMessagePolicy: FallbackToLogsOnError
          livenessProbe:
            httpGet:
              path: /healthz
              port: debug
              scheme: HTTP
            initialDelaySeconds: 300
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: debug
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 3080
              name: http
            - containerPort: 3090
              name: http-internal
            - containerPort: 6060
              name: debug
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 8Gi
              memory: 4G
            requests:
              cpu: "2"
              ephemeral-storage: 4Gi
              memory: 2G
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 101
            runAsUser: 100
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
