apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/utils/migrator

patchesJson6902:
  - target:
      version: v1
      kind: Job
      name: migrator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - upgrade
          - -from=v3.36
          - -to=v4.0

# Update env vars for migrator at the end of this file
configMapGenerator:
  - name: sourcegraph-frontend-env
    behavior: merge
    literals:
      - ENV_VAR=VALUE
