apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - patches/frontend.BackendConfig.yaml
patchesStrategicMerge:
  - patches/frontend.Service.yaml
  - patches/frontend-internal.Service.yaml
  - patches/frontend.Ingress.yaml
