apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
components:
  - ../../../components/monitoring
  # Use resources for a size-XS instance
  - ../../../components/sizes/xs
  - ../../../components/clusters/gke/configure
  - ../../../components/enable/service-discovery
